name = "Atak"
uuid = "ea1fb407-d168-472b-9d3b-6f44c48cad5b"
version = "0.1.0"
authors = ["ken-morel <engonken8@gmail.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
IonicEfus = "285369d7-3617-4bce-982e-acda657aee64"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[compat]
Dates = "1.11.0"
FunctionWrappers = "1.1.3"
JLD2 = "0.5.13"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
